pkg/retriever/retriever_test.go
This was somehow missed, but the retriever tests were not passing because of a bad reference. This was caused by a greater problem that I've outlined in our [Lassie Design issue](https://github.com/filecoin-project/lassie/issues/10#issuecomment-1371269542) about having duplicate types declared.
=> fix: use correct RetrievalSubscriber reference in MockClient function

pkg/client/client.go
Removes the unused `graphSync` and `transport` properties from the RetrievalClient. They were only used to construct the `dataTransfer` instance in the constructor of the client.
Resolves issue #12
=> chore: remove unused RetrievalClient properties

pkg/eventrecorder/eventrecorder.go
Currently building an endpoint to accept retrieval event posts from Autoretrieve - needed to copy over the structs in order to get the types to be correct. Less duplication if they can be imported instead.
Open to suggestions if there is a cleaner way to accomplish this! 
[(code that needs to use these structs)](https://github.com/application-research/estuary-metrics/pull/20/files#diff-ff820fd9ded186d77e7ea155fe6cdd28fdba5d2d0a9b638fdd38b8767ba09702R57)
=> feat: export the eventrecorder structs

pkg/retriever/retrieve.go, pkg/retriever/retrieve_test.go, pkg/retriever/retriever.go, pkg/retriever/sptracker.go, pkg/retriever/sptracker_test.go
* QueryResponse for this retrieval isn't acceptable
* Failure has occurred, either in query or retrieval
Allows the SP to be attempted again.
---
Came up during discussion on the autoretrieve problems and what the main differences are between "new lassie" and "old lassie". This is one, where removing the ActiveRetrievalsManager removed the fine-grained concurrency tracking (I think).
Without this change, the list of SPs that we end up with after filtering the indexer list are blocked from being talked to again until we finish the whole retrieval process and get either a final success or fail on all of them.
It may be worth discussing how much this is really worth it - if they are giving a QR saying they only do paid retrievals, what are the chances that they'll do it again? Probably high, …
=> feat: reduce concurrency for SPs who drop out early from retrieval process

pkg/retriever/retrieve.go, pkg/retriever/retrieve_test.go, pkg/retriever/retriever.go, pkg/retriever/sptracker.go, pkg/retriever/sptracker_test.go
This is the same commit as in #46 but that PR targetted `rvagg/events-consolidation` which was merged but not deleted so the PR didn't get auto-retargetted to `main` but instead was merged into a dead branch and is not on main!
=> feat: reduce concurrency for SPs who drop out early from retrieval process (dupe of #46)

cmd/lassie/fetch.go, go.mod, go.sum, pkg/client/client.go, pkg/retriever/retrievalclient.go, pkg/retriever/retrieve.go, pkg/retriever/retrieve_test.go, pkg/retriever/retriever.go, pkg/retriever/retriever_test.go, pkg/retriever/testutil/mockclient.go
Allows for separate, or combined block storage for each retrieval.
Uses https://github.com/filecoin-project/go-data-transfer/pull/362, will be draft until that's merged.
=> feat: require LinkSystem argument for each retrieval

server/http/ipfs.go
Ref: https://github.com/filecoin-project/lassie/pull/52#pullrequestreview-1280210150
@lidel
=> fix: header name, and expand on TODO note

pkg/metrics/metrics.go, pkg/retriever/executor.go, pkg/retriever/retriever.go
Currently, DAG Store issues, and other query errors from the provider show up in metrics as "filtering" on a query. I think this is a mistake. They're a failure. It's making the query success rate look artificially high (96+% when it's actually nearer to 80%) and this isn't good for our ability to track errors or for golden retriever. We should subtract them from the successful query count and not record them as just candidates that got filtered.
- Handle QueryResponseError status seperately in executor
- Pass the "Message" parameter as the error
- We can now combine the "QueryResponseMetricMatches" & "QueryErrorMetricMatches" into one
- Simplifies queryasked event handling as well.
=> Treat query response errors as query failures

.github/workflows/release-binaries.yml
Updates the GitHub release-binaries workflow to include the version in the `version.json` in the binary build via `ldflags`. This version is used in the output of the `lassie version` command.
=> Add version to release build

cmd/lassie/fetch.go, go.mod, pkg/eventrecorder/eventrecorder_test.go, pkg/indexerlookup/candidatefinder.go, pkg/indexerlookup/options.go, pkg/lassie/lassie.go, pkg/retriever/executor_test.go, pkg/retriever/retriever.go, pkg/retriever/testutil/mockcandidatefinder.go, pkg/types/types.go
Implement the capability to find retrieval candidates for a given CID asynchronously using the new IPNI `ndjosn` APIs. The changes introduce an async variation of `FindCandidates` to the `retriever.CandidateFinder` interface.
Introduce options to indxer-lookup implementation and refactor the hardcoded defaults across the code.
Fix a couple of bugs in indexer-lookup implementation of candidate finder, namely:
* Set the mime-type correctly in request; use `Accept` header instead of `Content-Type`. The latter is for response, not needed in request.
* Decode metadata as whole, since it may contain multiple protocols. This would have resulted in false negative errors and ultimately exclusion of candidates that support multiple protocols including GraphSync.
=> Implement asyc find candidate over IPNI `ndjson` APIs

pkg/indexerlookup/candidatefinder.go
Fix a bug where the scanner does not break out of loop when `io.EOF` is reached. Note that `scanner.Err()` does not return error on EOF.
Many thanks to @kylehuntsman for pointing this out.
=> Break scanning loop on EOF

go.mod, go.sum
introduced untagged version in #83, this is the now tagged version of ~same
=> deps: go-ipld-prime@v0.20.0 (for dagcbor streaming decode)

pkg/retriever/bitswapretriever_test.go, pkg/retriever/graphsyncretriever_test.go, pkg/retriever/retriever_test.go
mainly using `t.Parallel()` in conjunction with increasing times for some time-based tests to deal with slow CI making them flaky
=> fix: improve flakes, make test runs faster

cmd/lassie/daemon.go, cmd/lassie/fetch.go, cmd/lassie/flags.go, cmd/lassie/main.go
Adds `EventRecorder` configuration flags to the `daemon` and `fetch` CLI commands to enable sending retrieval events off to an event recorder API.
A single `setupLassieEventRecorder()` function was created in `/cmd/lassie/main.go` to encapsulate the logic for setting up the `EventRecorder` to ensure consistent setup across CLI commands.
- **--event-recorder-url**: The URL of the event recorder API. Including this flag in either command will kick off the creation of an `EventRecorder` and subscribe it with the provided `Lassie` instance.
- **--event-recorder-auth**: The authentication token for the event recorder API. This flag is not required when using `--event-recorder-url`, as the `EventRecorder` is aware that if the token is an empty string an `Authorization` header will not be added …
=> Add EventRecorder configuration flags

pkg/server/http/ipfs.go
For debugging and troubleshooting, there is no way for the the HTTP use case to pass trace IDs along to Lassie to corrolate specific requests with related logs. This updates the IPFS handler to accept an `X-Request-Id` header that could be used to corrolate logs with a request.
We currently use a `RetrievalID` to uniquely identify our fetches across the stack. This doesn't pair well with the idea that the user can provide their own unique ID, as we use that unique ID to correlate events. The user could break the Retrievers if the same unique ID was used for multiple requests and passed along as the unique identifier of a retrieval.
Because passing the `X-Request-Id` value through the stack would take a little more thought to implement correctly without breaking the Retrievers, the minimum …
=> Accept X-Request-Id request header and log corrolation to retrieval ID

pkg/indexerlookup/candidatefinder.go, pkg/indexerlookup/options.go
Add option to cascade lookups onto the DHT for both streaming and non streaming requests.
=> Refactor hard-coded DHT cascade query string into option

pkg/server/http/ipfs.go
Request is to use 504 for all our timeouts / failure to retrieve. Realize this global switch may cover some true 500s but all indications are that the vast majority are failure to retrieve (within timelimit or having exhausted solutions). We should get more fine grained later
=> Switch errors to 504

go.mod, go.sum, pkg/eventrecorder/eventrecorder_test.go, pkg/internal/testutil/mockclient.go, pkg/retriever/graphsyncretriever_test.go, pkg/retriever/retriever_test.go
while I was in there, this was bugging me
=> fix: remove quicktest

cmd/lassie/main.go, pkg/eventrecorder/eventrecorder.go, pkg/eventrecorder/eventrecorder_test.go, pkg/events/events.go, pkg/types/types.go
Enable publishing logs of indexer events, we will need this data.
- Make disabling optional
- Add recording of details
- Write tests to verify behavior
=> Dispatch indexer events

cmd/lassie/daemon.go, pkg/internal/itest/bitswapfetch_test.go, pkg/internal/streamingstore/streamingstore.go, pkg/internal/streamingstore/streamingstore_test.go, pkg/server/http/ipfs.go, pkg/server/http/server.go
Request from Saturn (their OS tmp directory is very small): allow the user to configure the directory used for storing temporary files while streaming
-- Add a tempdir flag to the daemon command, pass it through
-- tested and verified manually (no tests on http server still)
=> Make temp files dir configurable

pkg/internal/itest/bitswapfetch_test.go, pkg/internal/itest/client_query_test.go, pkg/internal/itest/client_retrieval_test.go, pkg/internal/itest/httpdaemon_test.go, pkg/internal/itest/mocknet/mocknet.go, pkg/internal/itest/unixfs/directory.go, pkg/internal/itest/unixfs/generator.go
I'll merge this into #100 soon, still tinkering in here.
Paving the way for selector support - we have some non-trivial UnixFS structures being synced and checked here. When a selector is applied we should be able to check that we get just the pieces we want.
=> itest: more unixfs cases

cmd/lassie/daemon.go, pkg/internal/itest/bitswapfetch_test.go, pkg/internal/itest/httpdaemon_test.go, pkg/internal/libp2p.go, pkg/internal/limitstore/limitstore.go, pkg/internal/limitstore/limitstore_test.go, pkg/lassie/lassie.go, pkg/server/http/ipfs.go, pkg/server/http/server.go
fix #107 and add a maximum blocks sent per request to the daemon
- New limitstore, an ipld.Storage that errors after n unique block puts
- New libp2p options config for Lassie
- New command line args for the daemon (I know this is getting ridiculous, let's define a config file, but next ticket. Also, it's all env vars so what's the diff?)
- Too many params on the HTTPServe so now it has a config
- Add integration test for limiting blocks per response.
=> Saturn optimizations

cmd/lassie/fetch.go, pkg/internal/itest/direct_fetch_test.go, pkg/internal/lp2ptransports/lp2ptransports.go, pkg/internal/lp2ptransports/types.go, pkg/internal/lp2ptransports/types.ipldsch, pkg/retriever/directcandidatefinder.go, pkg/retriever/retriever.go
fix #114 and improve direct candidate retrievals in general
#114 occurred cause now that we have multiple protocols, we don't have any mechanism for figuring out what protocols each peer we're talking to speaks
This PR resolves this by significantly improving the former `explicitCandidateFinder`, now the `DirectCandidateFinder`.
First, we now support more than one peer! (uses --providers, seperated by a comma)
Now, for each peer we want to do direct retrievals with, we:
1. Connect to the peer
2. Examine whether they support the libp2p retrieval transports protocol (a boost protocol that identifies how an SP provides retrieval, potentially on a DIFFERENT libp2p host). If so, we use this protocol to identify exact mechanisms for retrieving over this protocol
3. If the protocol is not …
=> Build direct candidate finder

cmd/lassie/daemon.go, cmd/lassie/flags.go, pkg/metrics/exporter.go, pkg/server/http/server.go
* add a flag to register the exporter on the daemon http server
* include golang and process metric collectors with the exporter
=> Exposing metrics on daemon

cmd/lassie/daemon.go, pkg/client/client.go, pkg/lassie/lassie.go
With Lassie deployed across Saturn, we're seeing memory and performance issues across both Saturn nodes and SPs.
This has raised the profile of needing to fix our cancellation logic. When the context gets cancelled at a higher level in the Lassie code, the call to CloseDataTransferChannel has no effect when passed a cancelled context. And when a data transfer doesn't close properly, it continues to consume memory -- there is a go routine and in memory state.  This is true on both the SP side AND the Lassie side. We need a proper fix for cancellation, but for now, let's just use the quick fix contained here to make sure retrievals get cancelled. A proper fix for cancellation logic will be a top priority after Async candidate retrieval is done.
Additionally even if there are lot of L1s, we …
=> Resolve two vectors to expanding memory usage

cmd/lassie/daemon.go, cmd/lassie/fetch.go, cmd/lassie/flags.go, pkg/internal/itest/http_fetch_test.go, pkg/lassie/lassie.go, pkg/retriever/coordinators/race.go, pkg/retriever/retriever.go
Turn off the graphsync retrievals in Rhea to reduce burden on SPs
- global option to disable graphsync retrievals in Lassie struct, supported at CLI, and passed through the retriever
- when passed, we skip building graphsync
- we should probably also add a protocol filter to the assignable candidate finder at some point, but that is a tomorrow problem
- realized there was a small bug in the racer where if you didn't have any retrievers it just ran forever
- add integration test to verify functionality.
- left as 504 for now to indicate it's not an indexer fail.
=> Global option to disable graphsync retrievals

pkg/indexerlookup/candidatefinder.go, pkg/indexerlookup/candidatefinder_test.go, pkg/internal/candidatebuffer/candidatebuffer_test.go, pkg/internal/mockindexer/mockindexer.go, pkg/internal/testutil/gen.go, pkg/retriever/bitswaphelpers/indexerrouting_test.go, pkg/retriever/bitswapretriever_test.go, pkg/retriever/combinators/asyncsplitter_test.go, pkg/types/types.go
Previously, if we get a 404 from the indexer, we return nil for a channel, which will hang forever
- the fix is three lines in candidatesfinder.go
- at the same time, I felt it was important to start testing the indexer finding code against what we believe the indexer to return. As a result, I've added a "mock" indexer server that can be spun up and added unit tests for the indexer.
- we could also incorporate this into integration tests with mocknet if we like, to make them "more integration-ey"
=> Fix async not found behavior

pkg/client/client.go, pkg/internal/itest/client_query_test.go, pkg/internal/itest/client_retrieval_test.go, pkg/internal/itest/mocknet/mocknet.go, pkg/internal/itest/testpeer/generator.go, pkg/lassie/lassie.go
Found the cause of the weird 14k goroutines in some of our timed out tests. We didn't plumb the context through to the local graphsync and datatransfer instances of the Lassie client, so they weren't getting properly shut down at termination. Combined with the fact that we start 200 request tasks workers and 200 response task workers, this multiplies pretty quickly when we have lots of integration tests.
=> fix: plumb context through to client

go.mod, go.sum, pkg/client/client.go, pkg/internal/itest/http_fetch_test.go, pkg/retriever/bitswapretriever.go
This is in addition to #143 but it requires https://github.com/filecoin-project/go-data-transfer/pull/371
Once this is applied, running through all of the `TestHttpFetch` itest leaves no lassie-related goroutines running. Aside from the bitswap resources, there's an fsm goroutine per datatransfer channel that stays alive.
=> fix: stop network resources

pkg/aggregateeventrecorder/aggregateeventrecorder.go, pkg/aggregateeventrecorder/aggregateeventrecorder_test.go, pkg/events/events.go, pkg/retriever/retriever.go, pkg/retriever/retriever_test.go, pkg/types/types.go
Adds an aggregate event recorder subscriber that aggregates retrieval events before POSTing to the event recorder endpoint.
- Adds a new AggregateEvent that is emitted to the configured event recorder endpoint instead of the single events
- Adds a new phase, `FetchPhase`, which encompasses the idea of the entire fetch from start to end.
- Adds a new event, `Finished`, which represents the end of the `FetchPhase`
```golang
type AggregatedEvent struct {
InstanceID        string    `json:"instanceId"`        // The ID of the Lassie instance generating the event
RetrievalID       string    `json:"retrievalId"`       // The unique ID of the retrieval
StorageProviderID string    `json:"storageProviderId"` // The ID of the storage provider that served the retrieval content
TimeToFirstByte …
```
=> Add aggregate event recorder subscriber

pkg/retriever/bitswapretriever.go, pkg/retriever/bitswapretriever_test.go
Currently we dispatch a "started event" for every bitswap retrieval, even when there are no bitswap candidates. This seems wrong and leads to confusing metrics.
Moves "Started" dispatch below receiving first indexer candidate.
=> No started event when candidates are not present for bitswap

pkg/retriever/assignablecandidatefinder.go, pkg/retriever/assignablecandidatefinder_test.go, pkg/retriever/graphsyncretriever.go, pkg/retriever/retriever.go, pkg/retriever/retriever_test.go
We're filtering a ton of requests on Saturn cause they're getting hit by concurrency limits and miner suspensions. Let's not do that. 
- Change "IsAcceptableIndexerCandidate" to "FiltererIndexerCandidate" that can remove 1 or more protocols from a candidate if now is not a reasonable time to use those protocols for those candidates.
- Modify Assignable candidate finder to work with it
- Move the type from graphsync retriever since... yea it's a bit absurd it lives there
It's pretty tough to test this with the retriever test the way it is -- I'm gonna take that on next and see if I can't clean it up.
=> Remove Bitswap concurrency limits

pkg/eventrecorder/eventrecorder.go
Maintain compatibility with current recorder schema until it changes. We want to cut an interim lassie release and currently many of the event posts fail whenever a fetch is included (and writes of batches are all or nothing I think)
Just ignore the fetch phase on the old recorder for now. We can put it back in once the schema on the other side supports it.
=> Drop fetch phase on old recorder

go.mod, go.sum
Download some stuff from web3.storage with recent libp2p websockets fix
I tested and was able to download a file successfully!
=> Update libp2p v0.26.3 to fix websockets

pkg/net/host/host.go
Fix #160
Let libp2p setup the addresses, based on transports.
=> Don't set default addresses

cmd/lassie/daemon.go, cmd/lassie/fetch.go, cmd/lassie/flags.go, pkg/lassie/lassie.go, pkg/retriever/retriever_test.go, pkg/session/config.go, pkg/session/session.go
Allow excluding providers from the command line via block list
-- replace outdated config names
-- add to top level lassie struct with opts
-- add to CLI
tested experimentally through CLI for now.
=> Pipe block list through to CLI

pkg/internal/itest/client_retrieval_test.go, pkg/internal/itest/mocknet/mocknet.go, pkg/retriever/graphsyncretriever.go, pkg/retriever/proposal.go, pkg/retriever/proposal_test.go
From `#boost-help` on Filecoin Slack:
Not sure if this is Lassie or not, but it turns out that it could be if you're doing anything other than the default selector. We only ever send ExploreAllRecursively, which isn't right if you have a path or change the depth type.
=> fix: pass actual selector to proposal

go.mod, go.sum, pkg/internal/testutil/collectingeventlsubscriber.go, pkg/retriever/graphsyncretriever.go, pkg/retriever/graphsyncretriever_test.go, pkg/retriever/prioritywaitqueue/prioritywaitqueue.go, pkg/retriever/prioritywaitqueue/prioritywaitqueue_test.go, pkg/retriever/retriever_test.go
Closes: https://github.com/filecoin-project/lassie/issues/171
Depends on https://github.com/rvagg/go-prioritywaitqueue/pull/1 (need to tag)
There is only an **initial** pause, after the first one it won't pause any more. I think this makes sense because we should get all Graphsync SPs in one batch, then try to connect to them all at once and proceed to `Wait()` on each of them.
An alternative is to go with "if no others queueing, always wait X duration", but I'm not sure that makes sense?
Also, default of 2ms. Does that make sense for these, can we expect to see Connect's in that timeframe? I don't know because I'm on garbage internet with a >=120ms latency to anywhere but my country, so 2m feels awfully fast to me!
=> feat: add initial pause for queue to collect connected SPs

pkg/aggregateeventrecorder/aggregateeventrecorder.go, pkg/aggregateeventrecorder/aggregateeventrecorder_test.go, pkg/events/events.go, pkg/internal/testutil/gen.go, pkg/retriever/retriever.go
Adds data about retrieval attempts to the events emitted by the aggregated event recorder to be able to compile metrics for the stats listed in #152.
Adds a new `RetrievalAttempt` struct for recording individual retrieval attempts
```golang
type RetrievalAttempt struct {
StorageProviderID string `json:"storageProviderId,omitempty"`
Error             string `json:"error"`
}
```
Adds the following properties to the `AggregatedEvent` struct:
```golang
type AggregateEvent struct {
...
TimeToFirstIndexerResult  int64              `json:"timeToFirstIndexerResult,omitempty"` // Time we received our first "CandidateFound" event
IndexerCandidatesReceived uint64             `json:"indexerCandidatesReceived"`          // The number of candidates received from the indexer
IndexerCandidatesFiltered …
```
=> Add retrieval attempt stats

pkg/retriever/graphsyncretriever.go, pkg/retriever/graphsyncretriever_test.go
Deduplicates candidates in the graphsync retriever by storing a map of peer IDs we've started retrievals for to candidate metadata. If we've stored metadata about a candidate before, we don't start another retrieval. Metadata is then referenced in the wait queue's compare function so that priority is based on the best metadata for a given candidate.
Fixes #55
=> Dedupe graphsync candidates

cmd/lassie/fetch.go, pkg/internal/itest/direct_fetch_test.go, pkg/internal/itest/http_fetch_test.go, pkg/server/http/ipfs.go, pkg/types/request.go, pkg/types/types.go
Replaces the `depthType` fetch parameter to `car-scope` and adds a `root` (depthType 0) option. Depth type values were renamed to `root`, `file`, and `all`, for depth types `0`, `1`, and `all` respectively.
Closes #179
=> Add car-scope parameter to replace depthType

cmd/lassie/fetch.go, pkg/internal/itest/http_fetch_test.go, pkg/server/http/ipfs.go, pkg/types/request.go, pkg/types/types.go
Looks like we got the new parameter naming a bit off, it changed, now we have the final version.
=> Rename "root" to "block"

cmd/lassie/fetch.go, pkg/internal/itest/direct_fetch_test.go, pkg/lassie/lassie.go, pkg/server/http/ipfs.go
The caller of Lassie fetch should be able to pass a per request callback
- Add as a parameter and pass through
- Add to places Lassie.Fetch is called
=> Add events calllback function parameter to Lassie.Fetch

pkg/server/http/ipfs.go
Removes the depth type HTTP parameter parsing. We can merge this once we know Saturn is sending car-scope instead of depth type.
Closes #187
=> Removes depth type HTTP parameter

cmd/lassie/fetch.go, pkg/internal/itest/http_fetch_test.go, pkg/retriever/assignablecandidatefinder.go, pkg/retriever/assignablecandidatefinder_test.go, pkg/server/http/ipfs.go, pkg/types/request.go
Adds a providers parameter to set fixed providers on a per request basis. Oft requested feature.
=> Allow overridden fixed peers per request

pkg/server/http/ipfs.go, pkg/server/http/server.go
The response status logging in the ipfs handler was accomplished through `fmt.Print()` with the idea that it was application level "UI" rather than logging. This has ultimately just led to console and log spam. This PR updates the response status logging to use INFO level logging, along with some minor opinionated refactoring of relevant variables and structs.
Closes #85
=> Log http response statuses at an info log level

cmd/lassie/main.go
This reverts the use of the aggregate event recorder to the event recorder without reverting any of the other commmits between v0.8.2 - v0.9.0. The instance was swapped in PR #218. That PR had no other edits to anything outside of the aggregate event recorder.
=> Revert use of pkg/aggregateeventrecorder to pkg/eventrecorder

pkg/internal/itest/http_fetch_test.go, pkg/server/http/client_close_test.go, pkg/storage/cachingtempstore.go
Fixes: https://github.com/filecoin-project/lassie/issues/211
I believe the issue in #211 is that client cancellation leaves open a brief window between request context cancel propagation through the retrieval system and the response cleanup by the http server, leading to a Write to a buffer that no longer exists.
I've added a test that simulates this and although it doesn't hit it perfectly each time it'll be quite flaky (50/50) when the problem persists. I started this test off as an itest, going through the whole http server setup and requesting with a client, and even though I could cause the exact panic, it was too unreliable for a test, so I've moved it closer and simulated the problem in the way I believe it's occurring.
The solution is to just stop the Write()s to the response as …
=> fix(http): address client cancellation panic

pkg/server/http/ipfs.go
Reported from Saturn:
```
fatal error: concurrent map writes
goroutine 8048914 [running]:
github.com/filecoin-project/lassie/pkg/server/http.ipfsHandler.func1.3({0x1831098, 0xc0268c0cf0})
/github/workspace/pkg/server/http/ipfs.go:250 +0x346
github.com/filecoin-project/lassie/pkg/retriever.makeOnRetrievalEvent.func1({0x1831098?, 0xc0268c0cf0?})
/github/workspace/pkg/retriever/retriever.go:226 +0x3ba
github.com/filecoin-project/lassie/pkg/retriever.collectResults({0x18252b0, 0xc001ee9600}, 0xc01c73f4c0, 0xc01b61dc20)
/github/workspace/pkg/retriever/graphsyncretriever.go:242 +0x1bf
github.com/filecoin-project/lassie/pkg/retriever.(*graphsyncRetrieval).RetrieveFromAsyncCandidates(0xc0147c0500, 0xc01b61dec0)
/github/workspace/pkg/retriever/graphsyncretriever.go:215 +0x458 …
```
=> fix(server-timings): lock header while inspecting/modifying Extra

pkg/retriever/prioritywaitqueue/prioritywaitqueue_test.go
I think the timings in these were a bit too bunched up for the low windows resolution and slower machines, this should space them out a bit. 🤞 I really don't want to have to use a mock timer in this.
=> fix: clearer timing boundaries for prioritywaitqueue tests

.github/workflows/release-binaries.yml, .goreleaser.yml
Use the more reliable go-releaser project that seems much more well developed than the one we're using and has been successful with other projects like go-car
I'm trying to just copy go-car configs, still confirming in tests that this works.
=> Update release process to use go-releaser

pkg/verifiedcar/verifiedcar.go
I was going to leave feedback about an extraneous go routine in verified car but I wanted to see if it worked first. It certainly appears to.
=> VerifiedCar: remove extraneous go-routine

pkg/internal/testutil/mockroundtripper.go, pkg/retriever/httpretriever_test.go
This is a little bit better I think, fewer stacked callbacks, no functions with long argument lists, a bit more Go-like and one less goroutine+channel in the chain.
This is a doubly-stacked PR, sorry, it's in to `rvagg/http-validation` which is in to `feat/http`. I'll retarget if necessary as things get merged.
=> fix(http): refactor MockRoundTripper

pkg/internal/itest/client_retrieval_test.go, pkg/internal/itest/direct_fetch_test.go, pkg/internal/itest/http_fetch_test.go, pkg/internal/itest/testpeer/generator.go, pkg/internal/itest/unixfs/directory.go, pkg/internal/itest/unixfs/generator.go, pkg/internal/itest/unixfs/namegen/namegen.go, pkg/server/http/client_close_test.go
I'm just going to park this here as one of my fun side-quests that's not complete. It comes from wanting to make more portable fixtures for unixfs selector variations and being able to define a set of blocks and a query into those blocks based on path. The core change here is just using a fixed corpus of random words to generate directory and file names.
But interestingly, it makes it _much_ more prone to encounter errors that I have seen when I was developing the unixfs fixturing stuff originally, but somehow managed to stamp out and haven't shown back up as flaky tests. I had suspicions at the time that there was something funky going on inside the traversal, or go-unixfsnode, or somewhere else, but managed to make it go away by massaging sizes and depths I think.
But now it's back, …
=> feat(test): file/dir name generator that's more realistic

pkg/internal/itest/http_fetch_test.go, pkg/internal/itest/mocknet/mocknet.go, pkg/internal/itest/testpeer/generator.go, pkg/internal/itest/testpeer/peerhttpserver.go
Adds HTTP integration tests that test that Lassie can fetch a valid car over the HTTP protocol. Remote HTTP peers are generated with an http multiaddress and run an HTTP server on that address for serving valid cars.
- `itest/testpeer/generator.go` can now generate HTTP peers with an HTTP server that returns valid cars
- `itest/testpeer/mocknet.go` has been updated to add HTTP peers
- Added `itest/testpeer/peerhttpserver.go` to create separate http server instances for each peer, as well as manage start and teardown appropriately.
=> Add HTTP integegration tests

cmd/lassie/fetch.go
`lassie fetch` was hard-coded to always use `cid.contact`. The changes introduce a new flag `--ipniEndpoint` to allow overriding the default endpoint used to discover content providers.
This feature is useful when debugging a local indexer instance or an explicit IPNI instance for content discovery/retrieval.
=> Add the ability to override default IPNI endpoint

cmd/lassie/fetch.go
Ref: https://github.com/filecoin-project/lassie/pull/234
we're not doing camelCase for these, so this is a consistency change
=> fix: s/ipniEndpoint/ipni-endpoint CLI arg

cmd/lassie/daemon.go, cmd/lassie/fetch.go, cmd/lassie/main.go, cmd/lassie/version.go, pkg/aggregateeventrecorder/aggregateeventrecorder.go, pkg/eventrecorder/eventrecorder.go, pkg/eventrecorder/filelogserver/filelogserver.go, pkg/indexerlookup/candidatefinder.go, pkg/internal/lp2ptransports/lp2ptransports.go, pkg/metrics/exporter.go, pkg/metrics/log.go, pkg/metrics/server.go, pkg/net/client/client.go, pkg/retriever/bitswaphelpers/indexerrouting.go, pkg/retriever/bitswaphelpers/log.go, pkg/retriever/bitswaphelpers/preloadcachingstorage.go, pkg/retriever/directcandidatefinder.go, pkg/retriever/graphsyncretriever.go, pkg/retriever/httpretriever.go, pkg/retriever/log.go, pkg/retriever/parallelpeerretriever.go, pkg/retriever/retriever.go, pkg/session/session.go, pkg/session/sptracker.go
Some loggers didn't have the `lassie/` prefix making it difficult to review Saturn logs and determine which logs were lassie related. I opted for the clean import of `github.com/ipfs/go-log/v2` and naming our Loggers `logger`.
=> Standardize logger vars and names

pkg/retriever/httpretriever.go
From this comment by @willscott: https://github.com/filecoin-project/lassie/pull/193#discussion_r1187500928
We use `"lassie"` as our default when talking to the indexer so it seems reasonable. We could add a version too?
=> fix(httpretriever): add client headers

pkg/internal/itest/http_fetch_test.go, pkg/server/http/ipfs.go, pkg/storage/deferredcarwriter.go, pkg/storage/deferredcarwriter_test.go
Fixes: https://github.com/filecoin-project/lassie/issues/243
While in here I found some problems with our existing headers that I've ironed out. One of the results was I replaced the incoming request path with go-ipld-prime's `datamodel.Path` implementation. The main change is it becomes more lenient, but also more consistent: https://github.com/ipld/go-ipld-prime/blob/b625f253fa5048f09c40a5240580849822cf601c/datamodel/path.go#L86-L120
so `/ipfs/bafyfoo/bar/////baz` works now and before, but before this change the `////` makes it through to some places we care about, like these headers. With this change it all gets made consistent, the user can still request a dodgy path and we'll handle it gracefully.
=> fix: http headers getting sent too late

cmd/lassie/fetch.go, pkg/internal/itest/direct_fetch_test.go, pkg/internal/itest/http_fetch_test.go, pkg/internal/itest/testpeer/generator.go, pkg/internal/testutil/mockroundtripper.go, pkg/retriever/httpretriever.go, pkg/retriever/httpretriever_test.go, pkg/server/http/ipfs.go, pkg/types/request.go, pkg/types/types.go
fix #238 - update to latest IPIP-402 renames, namely car-scope becomes dag-scope.
- rename carScope to dagScope throughout code base
- on incoming request handler, support both params being passed for now
- when making outgoing http requests, send both params for now (Web3.storage is not up to date)
=> Update car-scope to dag-scope

pkg/server/http/ipfs.go
This pulls out up all of the constants that are used in multiple places or controls behavior that is spec related. Also adds comments about spec decisions around supporting different parameters and header values.
=> Comment on spec related validation and pull out constants

pkg/server/http/ipfs.go
OMG THAT FUNCTION GOT LONG. I actually did this while doing the dups PR but didn't want to burden folks with additional code.
Basically, everywhere we parse and validate a request parameter, make that a seperate function that returns an validation err.
Then, everywhere we get a validation error, write out an error to the log and response in a single line utility function. There's probably an even simpler way to do this but this seems like a good improvement.
Also, I notice we sometimes return information in the response body about what went wrong but other times don't. I think we should always return this information, so I made sure the error is output in the response body in the error function.
=> Refactor main ipfs handler

pkg/internal/itest/http_fetch_test.go, pkg/retriever/httpretriever.go
Well folks, I guess this is why we integration test. Looks like we had a very missing trailing slash in the HTTP retrievals which will cause everything except for root cid retrievals to fail.
- Fix it
- Add integrations tests we never quite got to that sadly, probably would have caught this one
=> Fix http path retrievals

pkg/internal/itest/http_fetch_test.go
I wanted to verify we get the kind of failure we expect when a block is missing on a bitswap remote.
Add a test that removes a block from the remote and also lowers the timeout, confirm it fails and indicates an non-terminated stream.
=> Add test of fail on missing block

pkg/internal/itest/http_fetch_test.go
I meant to push this turned off when I originally added it but obviously went back and did more tinkering with it on and never turned it back off again. It's noisy, slows down the tests, and only useful if you're debugging DAGs.
=> chore: turn off debug in main itest

pkg/retriever/graphsyncretriever.go, pkg/retriever/httpretriever.go
Was left at `0`, so first goroutine in gets chosen. Not so important with so few http peers to select from currently but will become more important over time.
=> fix: add back waitqueue pause for http

pkg/internal/itest/http_fetch_test.go, pkg/retriever/bitswaphelpers/preloadcachingstorage.go, pkg/storage/duplicateaddercar.go
fix #276 
Basically, before we insert dups on dups=y, we need to make sure the CAR file we're verifying against has no duplicate puts due to protocol racing.
So, we simply don't add duplicate blocks to verification stream (that in turn inserts duplicates).
Honestly, this is all way too complicated. But it works.
=> fix(storage): insure no-dupes on protocol race when pre-filling dupes

go.mod, pkg/internal/itest/http_fetch_test.go, pkg/server/http/ipfs.go, pkg/types/request.go, pkg/types/request_test.go
Ref: https://github.com/ipfs/boxo/pull/303/commits/f61f95481041406df46a1781b1daab34b6605650#r1213918777
I'm not a great fan of the CID being in the hashed bit, but I believe that's what ipfs/boxo#303 is currently doing and it'd be nice to hamonise one way or the other, and it's not particularly wasteful to include it.
=> feat: add stable etag

pkg/lassie/lassie.go
We have an inadvertent HTTP timeout for fetches from HTTP providers. It's because we share the HTTP default client with the indexer fetcher, and that sets a 1 minute timeout.
- Use a unique client with the indexer
=> Use unique http client for indexer

pkg/retriever/bitswaphelpers/preloadcachingstorage.go
After writing a doc commit into @hannahhoward's #277 to clarify the preloader `Loader()` flow, I noticed a possible wasteful write @ https://github.com/filecoin-project/lassie/blob/2b3656be9b5cbe87b6616729b45eff4aca8e5565/pkg/retriever/bitswaphelpers/preloadcachingstorage.go#L311-L316
At that point, the `Loader()` call has failed to find the block in the parent or cache linksystems and it's not in the preload queue, so it's a new block that hasn't been encountered before and we load it from the "Fetcher" (bitswap) directly, bypassing any messy preload semantics. But after we have it, we write it both to the cache and to the parent. But, once it's in the parent, we shouldn't need it in the cache anymore. It's up to the user of the preloader to ensure that the parent linksystem is also able …
=> fix: simplify preloader logic

pkg/internal/itest/testpeer/generator.go
Closes: https://github.com/filecoin-project/lassie/issues/293
why not just do it eh?
=> test: ensure available port for test server

pkg/internal/itest/http_fetch_test.go
The flaky tests in CI are a 504, which should mean it's coming out of here: https://github.com/filecoin-project/lassie/blob/2edae8be9439dcf3395ae54ebcb002a5daa3c97e/pkg/server/http/ipfs.go#L235
The body should contain the error message.
=> test: extra debug output for flaky failure case

pkg/server/http/server.go
Looks like the pprof endpoints were accidentally removed in PR #286 while removing the metrics server and prometheus exporter. This commit adds them back to the HttpServer. Closes #297.
=> fix: add back pprof endpoints

pkg/server/http/ipfs.go
While our go integration tests showed our unterminated chunk code to indicate a premature close was working, curl and wire-shark showed a different story.
The old code was simply taking the conn and writing a "0\r\n" to it. However, it wasn't closing the conn, and because we hadn't told golang's HTTP code that we were taking over the conn, after our handler completed, go would still write the termination code: "0\r\n\r\n". So what we'd end up with is a response that ended "0\r\n0\r\n\r\n". 
after "0\r\n" is written, everything before \r\n is a trailer header. Go's HTTP client attempts to parse trailer headers, so when it read the second "0\r\n" it would error cause it's an incorrectly formatted header (the source of our weird "malformed MIME header" error message we've been seeing in …
=> Fix unterminated chunk code

go.mod
Having `require (` sections split up like this is a known bug that happen when you use both >= go1.18 and <= go1.17 together. Newer version of go preserve the require blocks differently because indirect imports were encoded in the same require block before.
To fix this I just remove all `) require (` to merge them in one mega block and then ran `go mod tidy` with an updated go toolchain. This creates two blocks, one for direct imports, one for indirect ones and makes `go.mod` easier to read.
=> chore: fix require blocks formating of the go.mod file

pkg/retriever/directcandidatefinder.go, pkg/verifiedcar/verifiedcar.go, pkg/verifiedcar/verifiedcar_test.go
Found 2 issues testing with booster-http:
1. we don't capture the http protocol when using the DirectCandidateFinder
2. we're currently incompatible with IPIP-402 for roots (see larger discussion)
- Add HTTP to decode of responses on libp2p/transports protocol
- Make roots checking optional for now
=> Fixes for Boost compatibility

cmd/lassie/fetch.go
These have been bugging me for a while; when in here I noticed the reason they seemed off is that one of these messages is wrong (the `> 0` vs `== 0`).
=> chore: clean up (and fix) messages from --provider flag

.github/workflows/release-binaries.yml
Failing CI because actions/checkout@v2 uses an old Node.js
=> ci: update checkout action version

pkg/indexerlookup/candidatefinder_test.go, pkg/internal/mockindexer/mockindexer.go
I'm attempting to deal with the flaky CandidateFinder test, which I can't replicate locally. I think the main problem here is that we tick the clock inside the test 1 minute per candidate, but the mock sleeps for 1 second per candidate.
The reasons this works most of the time is that the goroutine startup is fast enough to get started and get to the `clock.Sleep` _before_ the timer gets through its ticks. The mock clock will do an actual 1ms sleep for each `Add` to let the goroutine scheduler catch up, so for most cases we get enough breathing room to get at least one `clock.Add` in _after_ the `clock.Sleep`.
So there's two things going on in this PR:
1. Change test's clock tick to 1s
2. Add a channel into the mock that lets the test observe the incoming requests; for the async request it …
=> test: slow down CandidateFinder test to avoid clock race

cmd/lassie/daemon.go, cmd/lassie/daemon_test.go, cmd/lassie/fetch.go, cmd/lassie/fetch_test.go, cmd/lassie/flags.go, cmd/lassie/main.go, pkg/lassie/lassie.go
The goal here was to be able to call the daemon and fetch commands via handler functions that transform the flags into values so that they can be passed in programatically in a test. It didn't end up making any sense to have those functions return the Lassie isntance. Even if it did return Lassie, I'd have to somehow inspect Lassie behavior. I thought maybe it would be easier to inspect the configuration structs that were created instead.
If we can test that different flag inputs result in specific config values, then we can have other tests that check that passing different config values to lassie, the http server, and the event recorder result in specific behavior. I then made the functions for transforming the relevant flag values into the lassie config, http config, and event recorder …
=> Add CLI unit tests

cmd/lassie/daemon.go, cmd/lassie/daemon_test.go, pkg/internal/itest/http_fetch_test.go, pkg/server/http/server.go
Add a new configuration option to enable access-token-based authorization for all incoming HTTP requests.
Example use:
```
❯ go run ./cmd/lassie -- daemon --access-token supersecret
Lassie daemon listening on address 127.0.0.1:56251
Hit CTRL-C to stop the daemon
```
Unauthorized request:
```
❯ curl -i 'http://127.0.0.1:56251/debug/pprof/cmdline'
HTTP/1.1 401 Unauthorized
Date: Fri, 23 Jun 2023 09:13:57 GMT
Content-Length: 13
Content-Type: text/plain; charset=utf-8
Unauthorized
```
Authorized request:
```
❯ curl -i 'http://127.0.0.1:56251/debug/pprof/cmdline' -H 'Authorization: Bearer supersecret'
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 23 Jun 2023 09:13:30 GMT
Content-Length: 120
Warning: Binary output can mess up your terminal. …
```
=> feat: protect HTTP API using access token

pkg/retriever/bitswapretriever.go, pkg/retriever/bitswapretriever_test.go, pkg/server/http/ipfs.go, pkg/server/http/servertimingssubscriber.go
Pulls the `Server-Timing` response header logic into it's own file and updates the retrieval event parsing to get timing on individual retrieval attempts. This tracks the individual events that occur on a per retrieval basis, whereas before we were treating "retrieval" as a phase and tracking all events under that phase. This was problematic since the second event of any type, for example during a second concurrent retrieval, would overwrite any previous event and it's timings.
The following is an example of the `Server-Timing` response header when fetching `bafybeic56z3yccnla3cutmvqsn5zy3g24muupcsjtoyp3pu5pm5amurjx4/birb.mp4` via the daemon. I've added newlines for each comma delimited item.
```
Server-Timing: 
started-finding-candidates;dur=0.1301;candidates-found=179140830;candidates-fi …
```
=> feat: extract server timings and measure individual retrievals

cmd/lassie/daemon.go, cmd/lassie/fetch.go, cmd/lassie/flags.go, cmd/lassie/main.go, cmd/lassie/version.go
The verbose flags were both on the main lassie command and the subcommands, but after some investigation were found to only be affecting all of the listed logging subsystems when used on the subcommand. When the log levels were set as an action on the flag instead of relying on a global var to be set during a before hook, all the subsystems were affected as expected. Additionally, the list of logging subsystems that responded to the verbose flags was not updated during an update that normalized the naming convention of all the loggers.
Closes #327.
=> fix(cli): move log level logic to flag action

pkg/internal/testutil/gen.go, pkg/retriever/bitswapretriever.go, pkg/retriever/httpretriever.go, pkg/server/http/ipfs.go, pkg/storage/duplicateaddercar.go, pkg/verifiedcar/verifiedcar.go, pkg/verifiedcar/verifiedcar_test.go
Closes: https://github.com/filecoin-project/lassie/issues/336
* don't treat context cancellation as an ErrExtraneousBlock in the CAR verifier
* capture and properly handle block load errors that are missed by the go-ipld-prime traverser, ref: https://github.com/ipld/go-ipld-prime/pull/524
* fix flaky case(s) in verifiedcar test suite where multi-level sharded directory is assumed but only a single block dir is produced
The flaky one is really interesting, it became more flaky once we started properly and consistently reporting errors from the traversal, then it would flip between two error types. The fix was to ensure that the fixture data had a particular _shape_ because certain forms produce certain errors. Fun fun.
=> fix: various traversal and verifier fixes

cmd/lassie/fetch.go, pkg/server/http/ipfs.go, pkg/storage/cachingtempstore_test.go, pkg/storage/deferredstoragecar.go, pkg/storage/duplicateaddercar_test.go, pkg/storage/storage_test.go
fix #354
This is a somewhat naive fix, but i don't think it's totally unreasonable.
If you ask for `/ipfs/<cid>/path/to/file`
the root of the car you get back will, with this change, be `<cid>`.
I think the complexity that led to the current structure was a desire to have the root cid be `file`, but for validation and since the response car has blocks that are parents of `file`, it doesn't seem "incorrect" to say that the `root` of the structure in the car is `<cid>`.
ref: https://github.com/ipfs/specs/pull/402#discussion_r1220044618
=> include a root in car responses

pkg/aggregateeventrecorder/aggregateeventrecorder.go
rel: https://github.com/filecoin-project/lassie/issues/358
There's a "real" fix of figuring out why we can fail a specific retrieval attempt before emitting the `StartedRetrievalEvent` for that same event.
That said, this will be safer in terms of panics
=> gate assignment into a map

.goreleaser.yaml
Publish mac binary as "mac_os" rather than "darwin"
- Update go-releaseer.yaml
- Test locally
=> Update go mac binary name for releases

cmd/lassie/fetch.go, cmd/lassie/flags.go, pkg/aggregateeventrecorder/aggregateeventrecorder.go, pkg/build/version.go, pkg/lassie/lassie.go, pkg/net/host/host.go, pkg/server/http/ipfs.go
The goal was to take any constant or arbitrary strings and numbers and extract them for visibility with comments. Any constants where type defaults are used were ignored due to the large number of type defaults we utilize in an effort to keep clarity.
Closes #263
=> ref: extract magic numbers and strings into constants

pkg/internal/mockfetcher/mockfetcher.go, pkg/lassie/lassie.go, pkg/server/http/ipfs.go, pkg/server/http/ipfs_test.go, pkg/types/types.go
Adds daemon handler tests for making sure the daemon handler responds appropriately in error scenarios as well as testing that the RetrievalRequest object passed to the Fetch call is what is expected.
Closes #261
=> test: add ipfs handler response and fetch request tests

go.mod, go.sum
Update graphsync for v0.14.7, with a critical fix to a lock in the message loop for requests and responses
=> Update go-graphsync v0.14.7

README.md
Updates the README to describe why and how one would use lassie via the CLI, HTTP API, and library.
Close #320.
=> docs: add more usage detail to README

cmd/lassie/fetch.go, pkg/aggregateeventrecorder/aggregateeventrecorder_test.go, pkg/events/connectedtoprovider.go, pkg/events/failedretrieval.go, pkg/events/firstbyte.go, pkg/events/graphsyncaccepted.go, pkg/events/graphsyncproposed.go, pkg/events/manager_test.go, pkg/retriever/bitswapretriever.go, pkg/retriever/graphsyncretriever_test.go, pkg/retriever/httpretriever_test.go, pkg/retriever/parallelpeerretriever.go, pkg/retriever/retriever_test.go
Primarily for use with the CLI so you can see "Bitswap" where appropriate. events.Identifier() uses an interface check to get the SP ID and returns "" if the event doesn't have one and if it doesn't have a protocol; this means it returns "" for a lot of events where there could be a "Bitswap".
=> fix: add protocol detail to more events for better logging

cmd/lassie/fetch.go
Late change in https://github.com/filecoin-project/lassie/pull/373 after a review didn't catch this fact; explicitly making `spid` a string will prevent the b64("Bitswap") output, which is meaningless!
=> fix: "Bitswap" shouldn't convert peer.ID to display as b64

pkg/retriever/bitswapretriever.go, pkg/retriever/bitswapretriever_test.go, pkg/retriever/graphsyncretriever.go, pkg/retriever/parallelpeerretriever.go
Copypasta mistake in https://github.com/filecoin-project/lassie/pull/374
**Edit** cleaned this up a bit more and made more strict; also added proper "timeout" reporting for Bitswap because the event logs are full of Bitswap "context cancelled" which are just going to be (mainly) timeouts.
=> fix: properly detect context cancellation error type

cmd/lassie/fetch.go, cmd/lassie/fetch_test.go
8e45ccfa cleaned up pathing elsewhere, removing "/" prefixes, but left this undone. It means that a "/" prefix passes through the system and we end up with "//"; which is fine, except for the HTTP retriever which will fetch with a "//" prefix and be corrected by the server's `Location` header. This change does a parse, just like the daemon handler does, and strips out a "/" prefixe if it exists.
=> fix(cli): clean up path before passing it on

go.mod, pkg/internal/itest/http_fetch_test.go, pkg/internal/testutil/collectingeventlsubscriber.go, pkg/internal/testutil/mockroundtripper.go, pkg/retriever/bitswapretriever_test.go, pkg/retriever/httpretriever_test.go, pkg/retriever/retriever.go, pkg/retriever/retriever_test.go, pkg/server/http/ipfs.go, pkg/types/request.go, pkg/types/request_test.go
* When sending requests, we path-escape each segment before sending it (it turns out we have the same problem as https://github.com/web3-storage/dag.w3s.link/commit/e3c9a3146ed6d72e17f719426be32c459b4291f8 solves!)
* Adds a new `Request#GetDescriptorString()` method that is like `GetUrlPath()` but is more descriptive for logging purposes - the result can't be used safely as a URL string but it should be good for the case we currently have where it goes into aggregated events--with this path escape change, we record the escaped form in the database which makes it less obvious what the actual path is--with this change we store the actual requested path, plus we add a bunch of other information that we don't currently store about the incoming request.
* Changes `X-Ipfs-Path` response header …
=> Escape paths for HTTP requests

pkg/verifiedcar/verifiedcar.go, pkg/verifiedcar/verifiedcar_test.go
Ref: https://github.com/filecoin-project/lassie/issues/388 (doesn't close this, I still need to check our temp CAR storage that we're doing only MH lookups)
=> fix: compare multihash only in CAR verifier

.goreleaser.yaml
I've manually rebuilt assets in https://github.com/filecoin-project/lassie/releases/tag/v0.16.1 and https://github.com/filecoin-project/lassie/releases/tag/v0.17.0 using this and they run properly on older distros, notably [bullseye](https://github.com/filecoin-saturn/L1-node/blob/fc33a81af6bad0fe083ff00174755253fb0fde96/Dockerfile#L4).
=> fix: CGO_ENABLED=0 for static release builds

pkg/server/http/client_close_test.go, pkg/server/http/ipfs.go, pkg/server/http/ipfs_test.go, pkg/server/http/server.go
Saturn / other clients want to experiment with other http servers making using of lassie.
The IPFS Handler in the server/http package contains application logic for how to parse / render URLs that is reusable. The specific semantics of the HTTP server that this handler is currently attached to are specific to the lassie daemon mode - e.g. it may not be wnated to have the pprof debug endpoints on the same mux, or extra middleware like caching may be desired.
=> Export IpfsHandler

pkg/server/http/ipfs.go, pkg/server/http/ipfs_test.go
Ref: https://github.com/ipfs/specs/pull/435
=> fix: send 502 when no indexer candidates

pkg/internal/itest/http_fetch_test.go
While doing #386 I discovered that Go's HTTP client, once it discovers an unclean end, will immediately decide that the body shouldn't be read. So you have up until the moment of it discovering the unclean end to read the body, after that point you get an EOF.
I wish I saved the Go src where I found this, it might be worth me going back and finding it to confirm that I'm talking sense here.
I believe this explains occasional flakies like this one: https://github.com/filecoin-project/lassie/actions/runs/5960306260/job/16167386428?pr=383
The answer is to just not bother attempting to validate bodies in our integration tests when it's an unclean end. I kind of wish it were different because we do want to validate this, but without the ability to control timing, or change this behaviour, I …
=> fix: remove body validation from unclean termination

cmd/lassie/daemon.go, cmd/lassie/daemon_test.go
Closes #409 by adding the IPNI Endpoint Flag to the Daemon and adds a positive/negative test for the flag on the daemon.
Adding the positive/negative test required changing the exit command on 119 of daemon.go to pass the err on up.  Please review and confirm this won't introduce any unintentional side effects.
=> Add IPNI Endpoint Flag to Daemon

cmd/lassie/daemon.go, cmd/lassie/daemon_test.go, cmd/lassie/fetch_test.go, cmd/lassie/flags.go, cmd/lassie/main.go, pkg/internal/itest/http_fetch_test.go, pkg/lassie/lassie.go, pkg/retriever/bitswaphelpers/groupworkpool/groupworkpool.go, pkg/retriever/bitswaphelpers/groupworkpool/groupworkpool_test.go, pkg/retriever/bitswaphelpers/preloadcachingstorage.go, pkg/retriever/bitswapretriever.go, pkg/retriever/bitswapretriever_test.go
* Removes the per-retrieval preload concurrency handling
* Adds a per-Lassie concurrency pool which has a maximum number of parallel workers and a maximum number of workers _per "group"_; each retrieval is a "group"
* New default total bitswap concurrency is 32
* New default per-retrieval concurrency is 12
=> feat: add GroupWorkPool for managing global bitswap concurrency

.dockerignore, .github/workflows/publish-containers.yml, Dockerfile
Define Dockerfile to containerise Lassie binary in a minimal image.
Add CI job to build the container on PRs and publish a tagged version of it on:
* merge to main.
* github tags of `v*`.
* successful run of unified CI releaser.
=> Build and publish lassie container

Dockerfile
Now that we use static debian image as base, and the fact that lassie does not require CGO, disable CGO for faster build and smaller images.
=> Disable CGO in dockerfile

.github/actions/go-test-setup/action.yml, pkg/aggregateeventrecorder/aggregateeventrecorder.go, pkg/internal/itest/e2e_test.go, pkg/internal/itest/http_fetch_test.go, pkg/net/client/client_test.go, pkg/retriever/bitswapretriever_test.go, pkg/retriever/httpretriever_test.go, pkg/server/http/ipfs.go, pkg/server/http/servertimingssubscriber.go
Builds on #345 but is separate because this is a major refactor of `TestHttpFetch`, mainly just moving things around to make it slightly more readable.
Also adds some basic aggregateevent testing into the integration test so we can start to assert it reports things that we expect.
=> chore: big refactor of TestHttpFetch, add basic aggregateevent testing

pkg/internal/itest/e2e_test.go, pkg/internal/itest/trustless_fetch_test.go, pkg/server/http/server.go
already sick of this, it takes ~20 seconds to run locally when the packages are cache-ready and a pass result doesn't get cached between test runs.
=> chore: skip e2e test when not in CI

go.mod, go.sum, pkg/internal/itest/http_fetch_test.go, pkg/internal/itest/testpeer/generator.go, pkg/retriever/bitswapretriever_test.go, pkg/retriever/httpretriever_test.go, pkg/storage/duplicateaddercar.go
Ref: https://github.com/ipfs/go-graphsync/pull/442
Instead of relying on the transports to do what we ask wrt identity CIDs; handle it all locally and gate their handling right up to the output block stream.
This approach works with both an older graphsync and https://github.com/ipfs/go-graphsync/pull/443
=> fix: alternative identity CID handling

cmd/lassie/fetch.go
A legacy of switching to go-ipld-prime's datamodel.Path is that it doesn't prefix with '/' and this is one of the places we made the assumption it would come prefixed.
=> fix: prefix path with '/' for cli "Fetching bafy.../path"

cmd/lassie/fetch.go, cmd/lassie/flags.go, pkg/heyfil/heyfil.go, pkg/heyfil/heyfil_test.go, pkg/server/http/ipfs.go
One for you to review @willscott.
This ends up being a complete noop if none of the provided addresses look like they can be translated. So for current usage this is entirely transparent, but as soon as someone provides an `f0\d+` or just a plain peer ID, it'll try and use heyfil to fill in the blank.
I don't have a good example handy of a specific bit of content and a working SP, but this one _should_ work for some known content that the SP claims to be storing, using both forms:
=> feat: attempt translate filecoin SP-like provider addresses with heyfil

cmd/lassie/fetch.go, cmd/lassie/flags.go, pkg/heyfil/heyfil.go, pkg/heyfil/heyfil_test.go, pkg/server/http/ipfs.go, pkg/types/request.go, pkg/types/request_test.go
Where peer ID is not provided, we generate a random one for internal use.
Ref: https://github.com/filecoin-project/lassie/issues/418
One of the accidental outcomes of this is that it makes lassie into a really easy trustless **gateway** download client:
```
lassie fetch --provider http://ipfs.io bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze/wiki/Cat
```
Would be just like doing a `curl` with `Accept: application/vnd.ipld.car` but _also_ doing a full verification of the download so the trustless data can be trusted.
Note the 3 made-up peer IDs in there since none of the providers have them. Peer ID flows through the internal event system and is mainly used as a unique key and for reporting, so we need one (atm).
This also impacts `?providers` on the daemon, they'll be …
=> feat: allow missing peer ID & http:// url style on HTTP --providers

README.md, cmd/lassie/fetch.go, pkg/aggregateeventrecorder/aggregateeventrecorder.go, pkg/events/base.go, pkg/events/blockreceived.go, pkg/events/candidatesfiltered.go, pkg/events/candidatesfound.go, pkg/events/connectedtoprovider.go, pkg/events/failed.go, pkg/events/failedretrieval.go, pkg/events/finished.go, pkg/events/firstbyte.go, pkg/events/graphsyncaccepted.go, pkg/events/graphsyncproposed.go, pkg/events/manager_test.go, pkg/events/startedfetch.go, pkg/events/startedfindingcandidates.go, pkg/events/startedretrieval.go, pkg/events/succeeded.go, pkg/internal/testutil/collectingeventlsubscriber.go, pkg/retriever/assignablecandidatefinder_test.go, pkg/retriever/bitswapretriever_test.go, pkg/retriever/retriever.go, pkg/types/request.go, pkg/types/types.go
except in the case of data-transfer requests where this is the lingo for retrievals.
BREAKING only in that consumers of the internal event system will have trouble with this; otherwise we use "root" CID externally everywhere else already.
Closes: https://github.com/filecoin-project/lassie/issues/334
=> chore!: rename "payload" CID to "root" CID

cmd/lassie/fetch.go, cmd/lassie/fetch_test.go, pkg/storage/duplicateaddercar.go
Closes: https://github.com/filecoin-project/lassie/issues/335
draft because something's wrong with duplicates output from this; noticeable with nontrivial numbers of duplicate blocks and I'm not sure if this applies just to this new feature or if it also applies to the daemon
=> feat: --duplicates on CLI to putput duplicate blocks

pkg/internal/itest/http_fetch_test.go, pkg/retriever/bitswaphelpers/countinglinksystem.go, pkg/retriever/bitswaphelpers/multiblockstore.go, pkg/retriever/bitswaphelpers/preloadcachingstorage.go, pkg/retriever/bitswapretriever.go, pkg/retriever/parallelpeerretriever.go, pkg/retriever/resultcollector.go, pkg/retriever/retriever.go
The events callback is intended to be only ever called on the original Retrieve() goroutine; bitswap uses many goroutines so we reuse `retrievalShared` to do eventing and error/results collection like the other two retrievers.
Fixes: https://github.com/filecoin-project/lassie/issues/442
=> fix: run bitswap in a goroutine, collect & dispatch events in parent

pkg/indexerlookup/candidatefinder.go, pkg/retriever/bitswapretriever.go, pkg/retriever/bitswapretriever_test.go, pkg/retriever/graphsyncretriever.go, pkg/retriever/parallelpeerretriever.go, pkg/retriever/retriever_test.go
* replace some uses of multierr with fmt.Errorf's %w;%w
* fix up timeout error string inconsistencies: "timed out" vs "timeout"
as a result of checking the errors list with "Other" taking up a very large share, we have, in places 2 and 3:
```
retrieval failed; retrieval timed out after 20s
timeout after 20s
```
tbh I'm not actually sure why the former is now showing up more than the latter, I suspect it must have been something I did with the context juggling I've had to do
* https://github.com/filecoin-project/lassie/pull/374
* https://github.com/filecoin-project/lassie/pull/385
We're also getting this now:
```
failed to load root node: failed to load root CID: context canceled
```
Which is fine, but I think it would be preferable to show this as a timeout instead (i.e. parent retrieval …
=> chore: post Go 1.19 multi-error cleanup

README.md
This simply updates the README.
The go example was using lassie v0.17.0 and `types.DagScopeAll`, which was dropped in [v0.18.0](https://github.com/filecoin-project/lassie/commit/46dca4c01ea5dfbff700d7cab5d611336be7b3dc#diff-8e49337a1417a39a62ebf427e84fb2faa566c96e37ae627ac484c05dbe65c483L267) and now lives at `trustlessutils.DagScopeAll`. The behavior for `lassie.Fetch` also changed so that it cannot except `nil` options since these are variadic. Also, a couple of links were broken.
=> docs: update README's go example, link fixes

go.mod, pkg/internal/itest/e2e_test.go, pkg/server/http/ipfs.go
Strange behaviour causing e2e test failures when upgrading to 1.22, diagnosed as a different form that an HTTP server decodes a request and doesn't fully unescape its `Path` when it has special characters in it. This seems to be related to the new ServeMux changes in 1.22 because GODEBUG=httpmuxgo121=1 reverts the behaviour and the test passes.
The fix is to explicitly unescape the path before passing it on, go-trustless-utils will re-escape itself when it builds a new request to pass on downstream, but in the meantime we need to know the exact unescaped path so we can traverse it to validate the incoming data as well as pass it on upstream to the remote.
=> chore: upgrade Go to 1.22, adapt to http server URL changes
