filecoin-project/lassie

- pkg/retriever/retrieve.go
I was reading through the retriever code and trying to analyze what it was doing, and found I wanted to experiment with different simplications to check for understanding -- and it was easier to do so in a commit rather than a PR comment. Here are some things I did:
- removed activeQueryCancel entirely -- I'm not clear what this accomplishes, at least at this point. The relevant cancellation is this -- https://github.com/filecoin-project/lassie/blob/rvagg/newretriever-hannah-suggestions/pkg/retriever/retrieve.go#L115 -- which should shut down any active queries. I don't see any individual use of this any more
- got rid of the break named line stuff where I could (ultimately this made collectResults cleaner)
- seperated out the retrieveCandidate function, cause I found the canProceed …
> refactor(retriever): various simplications

- go.mod
- go.sum
- pkg/client/client.go
Add a function on the retrieval client to wait for data transfer migrations to finish and report errors (this is something that should have existed from the start)
> Handle awaiting for a data transfer migrations

- .github/workflows/release-binaries.yml
- LICENSE-APACHE
- LICENSE-MIT
- README.md
Add a very simple readme, licenses, and a task to compile binaries for download on release
> Add readme and binaries

- cmd/lassie/fetch.go
Lazily instantiate the CARv2 ReadWrite blockstore, so that no `.car` file is created when no candidates are found from which to retrieve.
Return any errors when finalizing the car blockstore.
Fixes #32
> Do not write CAR file when no candidates are found

- cmd/lassie/fetch.go
Implement a flag to specify an explicit provider from which to fetch a given CID from.
Fixes #50
> Implement fetch from explicit provider

- cmd/lassie/fetch.go
- server/http/ipfs.go
- version.json
I was holding off to fix this until we got streaming done but since we're pushing out a release then I think we should have this addressed to set expectations right.
verison bumped here too
> fix: write CARv1s only

- pkg/server/http/ipfs.go
Returns a 404 response when the `ErrNoCandidates` error is returned from `lassie.Fetch()`.
https://user-images.githubusercontent.com/3432646/219265096-0121e0d1-ee1e-4af6-808f-2d79a7193b53.mp4
> Return a 404 response when no candidates are found

- pkg/server/http/ipfs.go
I'm anxious this code path is even getting called, but it looks like there's a clear mistake in it (err parameter had no name, so scope of `err` used later was wrong)
Also, I put in a check so we don't write a status after the bytes are written.
> Fix panic in callback

- cmd/lassie/daemon.go
- cmd/lassie/fetch.go
- pkg/internal/streamingstore/streamingstore.go
also will try and remove even if `f.Close()` fails
Closes: https://github.com/filecoin-project/lassie/issues/123 (🤞)
> fix: remove temp files early where possible

- pkg/internal/candidatebuffer/candidatebuffer.go
Discovered we're panicing cause of not waiting for go routines to finish, meaning that we can accidentally get new providers sent to the callback after AssignableCandidateFinder.FindCandidates, which is not expected behavior. This in turn causes a panic in RetrievalWithCandidateFinder when a channel is closed before the last send.
> fix(candidatebuffer): fix panic vector

- pkg/indexerlookup/candidatefinder.go
- pkg/indexerlookup/options.go
Add option to cascade also to the legacy server with the indexer
- Add another indexer option similar to dht cascade
> Support legacy cascade

- pkg/internal/itest/http_fetch_test.go
- pkg/server/http/ipfs.go
Allow setting a block limit on a per request basis -- we want this in order to support differentiated block limits for raw requests.
- add logic to the handler
- add integration test to verify
> Allow blockLimit query parameter to set block limit per request

- go.mod
- go.sum
- pkg/server/http/ipfs.go
- pkg/server/http/server.go
First event from each phase is used for duration - subsequent are labeled as extra metadata
> Expose timings in http responses

- cmd/lassie/main.go
- pkg/aggregateeventrecorder/aggregateeventrecorder.go
- pkg/aggregateeventrecorder/aggregateeventrecorder_test.go
Finish off end to end aggregate events. Requires https://github.com/filecoin-project/lassie-event-recorder/pull/36
> Fix outstanding bugs in aggregate event recorder

- cmd/lassie/main.go
> Revert "Revert use of pkg/aggregateeventrecorder to pkg/eventrecorder"

- pkg/internal/itest/http_fetch_test.go
- pkg/server/http/ipfs.go
- pkg/server/http/server.go
> Send a bad chunk to signal error cases

- pkg/internal/testutil/gen.go
- pkg/verifiedcar/verifiedcar_test.go
Figured out one of our [flakies](https://github.com/filecoin-project/lassie/actions/runs/5110822000/jobs/9187137994?pr=253) was because we ended up with DAGs with dupes but we weren't expecting there to be when re-walking the DAG for validation.
The solution here is a little heavy handed, this would be best done in go-unixfsnode/testutil, but the surgery there to make it happen is more painful than doing it here. I think what I'd like to do is have something that handles options better than now because the current solution is to add another argument, break the API, and wire up some messy LinkSystem "Has()" checking. Messy.
```go
data := unixfs.Dir(t, lsys).
TargetSize(1<<20).
Sharded().
NoDuplicates().
Generate()
```
> fix: don't allow dupes in test DAGs where we don't expect them

- cmd/lassie/daemon.go
- cmd/lassie/fetch.go
- pkg/internal/itest/http_fetch_test.go
- pkg/internal/testutil/correctedmemstore.go
- pkg/internal/testutil/threadsafestore.go
- pkg/lassie/lassie.go
- pkg/retriever/bitswapretriever.go
- pkg/retriever/bitswapretriever_test.go
- pkg/retriever/httpretriever_test.go
- pkg/storage/duplicateaddercar_test.go
- pkg/types/request.go
- pkg/verifiedcar/verifiedcar_test.go
Closes: https://github.com/filecoin-project/lassie/issues/288
Draft for now because I haven't figured out the failing bitswap test—pre-populated linksystem fails to get proper results _with_ preloader.
> feat!: remove TempDir option; only rely on req.PreloadLinkSystem

- pkg/session/config.go
noticed the TODO that I'd left in there
> doc: document session Config fields

- pkg/internal/itest/testpeer/generator.go
Ran into a CI test error where there was a panic in [`generator.go`](https://github.com/filecoin-project/lassie/blob/92924796eba357c3412beb471f661f7c5d846c52/pkg/internal/itest/testpeer/generator.go#L273) when creating an HTTP remote peer when the address was already bound to. With the way the mocknet `Identity` struct is instantiated, the random port that is assigned to it's multiaddrress has the potential to be already bound.
From  [go-libp2p-testing/net/gen.go](https://github.com/libp2p/go-libp2p-testing/blob/aac9ce834b218b0d51ab729256812a1b4ea9164b/net/gen.go#L29-L33):
> // chances are it will work out, but it **might** fail if the port is in use
> // most ports above 10000 aren't in use by long running processes, so yay.
> // (maybe there should be a range of "loopback" ports that …
> Fix itest HTTP remote peer creation panic

- pkg/server/http/servertimingssubscriber.go
The metric and timing maps lock was originally locking around map reads instead of writes. Updated lock to lock all read and writes of the maps.
Closes #339
> fix(servertiming): lock map writes

- pkg/server/http/servertimingssubscriber.go
Caught a race when running tests locally. Updating `Extra` while go-server-timing is writing it is the problem, so I believe the solution is to use the internal go-server-timing header lock to synchronise.
> fix: use internal servertiming lock for synchronising

- pkg/internal/testutil/verifier.go
- pkg/retriever/graphsyncretriever.go
- pkg/retriever/graphsyncretriever_test.go
- pkg/retriever/httpretriever.go
- pkg/retriever/httpretriever_test.go
- pkg/retriever/parallelpeerretriever.go
- pkg/retriever/retriever_test.go
Fixes: https://github.com/filecoin-project/lassie/issues/343
> fix: don't sendEvent if context cancelled

- pkg/internal/itest/http_fetch_test.go
- pkg/server/http/ipfs.go
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server
Fixes: https://github.com/filecoin-project/lassie/issues/367
> feat: add Server header with version

- pkg/retriever/bitswapretriever.go
- pkg/retriever/parallelpeerretriever.go
_(stacked PR on top of #373)_
Gate the case where the retriever (parent) cancels a protocol retriever because another has completed successfully. If a retrieval fails in this case, it's not a failure that we should either report in the event system, or record against the SP's performance stats.
Fixes: https://github.com/filecoin-project/lassie/issues/364
I believe this fixes #364, but it's hard to reproduce reliably so I can't be sure.
> fix: don't record failures on context cancellation

- .github/workflows/release-binaries.yml
Ref: https://goreleaser.com/deprecations#-rm-dist
> fix: s/--rm-dist/--clean

- README.md
- cmd/lassie/fetch.go
- cmd/lassie/fetch_test.go
Closes: https://github.com/filecoin-project/lassie/issues/417
Should be additive and not change existing behaviour.
> feat: support lassie fetch /ipfs/bafy... style queries

- cmd/lassie/flags.go
- docs/HTTP_SPEC.md
- pkg/aggregateeventrecorder/aggregateeventrecorder.go
- pkg/internal/itest/testpeer/generator.go
- pkg/retriever/bitswapretriever.go
- pkg/types/types.go
> Text corrections

- .github/workflows/publish-containers.yml
Use new workflow location.
Replaces #469
> Update workflow from pl-strflt to ipdxco
